files:
  - source: /src/*/en/*.md
    translation: /src/%file_name%/%two_letters_code%/%original_file_name%
  - source: /src/*/*.md
    translation: /%original_path%/%two_letters_code%/%original_file_name%
